### ISSUE TITLE
UserStory 1

### ISSUE THREAD

**Issue by JuliaKathariina** [JuliaKathariina/capstone-project#1]
# Value Proposition
As a User, I want to land on the homepage and get a clear view of the different contents of the app.

# Description
The Apps Homepage should give an overview over the apps content.

![Unbenannt-2022-10-17-2048](https://user-images.githubusercontent.com/112406162/197723870-d06f64fa-43ea-405c-939d-f5f0dd5f30a1.png)

# Acceptance Criteria
- When I launch the application, I land on a page with buttons and a logo.
- The main page contains a button with a click function. A click on the button shows two texts. A click on the button takes me to page 1 or page 2.

# Tasks
 - [ ] create new React project
 - [ ] remove unnecessary data
 - [ ] add home function to app.js
 - [ ] add div to function
 - [ ] add a logo
 - [ ] add h1 to app.js
 - [ ] add a button with a click and select function

**Comment by dorosiemers** [comment]
Hey Julia, when you have a functioning button, it should already lead you to an existing page. You go girl!
