### ISSUE TITLE
UserStory 3

### ISSUE THREAD

**Issue by JuliaKathariina** [JuliaKathariina/capstone-project#6]
# Value proposition

As a user, I want to have on the map and a clear overview of each map .

# Description

In the main are different cards about healing stones.

![Unbenannt-2022-10-17-2048-3](https://user-images.githubusercontent.com/112406162/198561419-6457da58-b4d9-415e-8a11-5ddf55f7ea2b.svg)

# Acceptance criteria

- When I click on map on the main page, I am redirected to page1/map. There you can see different cards. 
- The user can scroll up and down to see different contents.

#Tasks

  - [ ] I create maps with static content
  - [ ] The cards will get images.
  - [ ] You can see a bar to scroll up and down.
